import { create } from "zustand";
import type { ConnectedService,ServiceId,AgentAction,ActionPlan,AuditEntry,ChatMessage,AuditEventType,RiskLevel,TokenHealth } from "@/types";
const uid=()=>Math.random().toString(36).slice(2,9),now=()=>new Date().toISOString();
const I:ConnectedService[]=[
  {id:"google",name:"Google Workspace",icon:"G",description:"Calendar, Gmail, Drive",gradient:"linear-gradient(135deg,rgba(66,133,244,.12),rgba(234,67,53,.08),rgba(251,188,4,.08))",iconColor:"#4285f4",connected:false,tokenHealth:"missing",scopes:[{id:"cal.read",label:"Read calendar",description:"View meetings",defaultRisk:"auto",enabled:true},{id:"cal.write",label:"Create events",description:"Schedule",defaultRisk:"confirm",enabled:true},{id:"mail.read",label:"Read email",description:"Search",defaultRisk:"auto",enabled:true},{id:"mail.send",label:"Send email",description:"Send as you",defaultRisk:"approve",enabled:true}]},
  {id:"slack",name:"Slack",icon:"S",description:"Channels, messages",gradient:"linear-gradient(135deg,rgba(97,45,153,.12),rgba(224,30,90,.06))",iconColor:"#611F69",connected:false,tokenHealth:"missing",scopes:[{id:"ch.read",label:"View channels",description:"See channels",defaultRisk:"auto",enabled:true},{id:"msg.read",label:"Read messages",description:"Read history",defaultRisk:"auto",enabled:true},{id:"msg.write",label:"Post messages",description:"Send",defaultRisk:"confirm",enabled:true},{id:"usr.read",label:"View members",description:"See team",defaultRisk:"auto",enabled:true}]},
  {id:"github",name:"GitHub",icon:"GH",description:"Repos, issues, PRs",gradient:"linear-gradient(135deg,rgba(140,140,160,.1),rgba(90,90,110,.06))",iconColor:"#8b949e",connected:false,tokenHealth:"missing",scopes:[{id:"repo.read",label:"Read repos",description:"View code",defaultRisk:"auto",enabled:true},{id:"iss.write",label:"Create issues",description:"Open issues",defaultRisk:"confirm",enabled:true},{id:"pr.review",label:"Review PRs",description:"Add reviews",defaultRisk:"approve",enabled:true},{id:"pr.merge",label:"Merge PRs",description:"Merge code",defaultRisk:"stepup",enabled:true}]},
];
interface S{services:ConnectedService[];connectService:(id:ServiceId)=>void;disconnectService:(id:ServiceId)=>void;toggleScope:(s:ServiceId,sc:string)=>void;riskOverrides:Record<string,RiskLevel>;setRiskOverride:(s:ServiceId,sc:string,r:RiskLevel)=>void;getEffectiveRisk:(s:ServiceId,sc:string)=>RiskLevel;currentPlan:ActionPlan|null;setPlan:(p:ActionPlan)=>void;updateAction:(id:string,u:Partial<AgentAction>)=>void;clearPlan:()=>void;auditLog:AuditEntry[];addAudit:(t:AuditEventType,m:string,e?:Partial<AuditEntry>)=>void;messages:ChatMessage[];addMessage:(m:Omit<ChatMessage,"id"|"timestamp">)=>void;getHistory:()=>{role:string;content:string}[];thinking:boolean;setThinking:(v:boolean)=>void;activeTab:"services"|"actions"|"audit"|"rules";setActiveTab:(t:S["activeTab"])=>void;mobilePanel:"chat"|"dashboard";setMobilePanel:(p:S["mobilePanel"])=>void}
export const useStore=create<S>((set,get)=>({
  services:I.map(s=>({...s,scopes:s.scopes.map(sc=>({...sc}))})),
  connectService:(id)=>{set(s=>({services:s.services.map(v=>v.id===id?{...v,connected:true,connectedAt:now(),tokenHealth:"active" as const}:v)}));get().addAudit("service_connected",`Connected ${get().services.find(s=>s.id===id)?.name}`,{service:id});},
  disconnectService:(id)=>{set(s=>({services:s.services.map(v=>v.id===id?{...v,connected:false,connectedAt:undefined,tokenHealth:"revoked" as const}:v)}));get().addAudit("service_disconnected",`Disconnected ${get().services.find(s=>s.id===id)?.name}`,{service:id});},
  toggleScope:(sid,scid)=>{set(s=>({services:s.services.map(v=>v.id===sid?{...v,scopes:v.scopes.map(sc=>sc.id===scid?{...sc,enabled:!sc.enabled}:sc)}:v)}));const sc=get().services.find(s=>s.id===sid)?.scopes.find(s=>s.id===scid);get().addAudit(sc?.enabled?"scope_granted":"scope_revoked",`${sc?.enabled?"Enabled":"Disabled"} ${sc?.label} on ${sid}`,{service:sid,scope:scid});},
  riskOverrides:{},
  setRiskOverride:(sid,scid,r)=>{set(s=>({riskOverrides:{...s.riskOverrides,[`${sid}.${scid}`]:r},services:s.services.map(v=>v.id===sid?{...v,scopes:v.scopes.map(sc=>sc.id===scid?{...sc,userRisk:r}:sc)}:v)}));get().addAudit("risk_rule_changed",`${sid}/${scid} → ${r}`,{service:sid,scope:scid,riskLevel:r});},
  getEffectiveRisk:(sid,scid)=>get().riskOverrides[`${sid}.${scid}`]??get().services.find(s=>s.id===sid)?.scopes.find(s=>s.id===scid)?.defaultRisk??"approve",
  currentPlan:null,setPlan:p=>set({currentPlan:p}),updateAction:(id,u)=>set(s=>({currentPlan:s.currentPlan?{...s.currentPlan,actions:s.currentPlan.actions.map(a=>a.id===id?{...a,...u}:a)}:null})),clearPlan:()=>set({currentPlan:null}),
  auditLog:[],addAudit:(t,m,e)=>set(s=>({auditLog:[{id:uid(),type:t,message:m,timestamp:now(),...e},...s.auditLog]})),
  messages:[{id:"w",role:"assistant",content:"Welcome to Mandate. Connect services to define my authority.\n\nEvery action requires your permission.\n\nYour mandate. Your rules.",timestamp:now()}],
  addMessage:m=>set(s=>({messages:[...s.messages,{...m,id:uid(),timestamp:now()}]})),getHistory:()=>get().messages.slice(-20).map(m=>({role:m.role,content:m.content})),
  thinking:false,setThinking:v=>set({thinking:v}),activeTab:"services",setActiveTab:t=>set({activeTab:t}),mobilePanel:"chat",setMobilePanel:p=>set({mobilePanel:p}),
}));
