"use client";
import { useState } from "react";
import { Link2,Unlink,Check,X,ShieldAlert,RotateCcw,AlertCircle,Zap,ScrollText,Download,Loader2,Settings2 } from "lucide-react";
import { useStore } from "@/lib/store";
const ec:Record<string,{I:any;c:string}>={service_connected:{I:Link2,c:"text-m-mint"},service_disconnected:{I:Unlink,c:"text-m-rose"},scope_granted:{I:Check,c:"text-m-mint"},scope_revoked:{I:X,c:"text-m-copper"},action_auto_executed:{I:Zap,c:"text-m-mint"},action_approved:{I:Check,c:"text-m-mint"},action_rejected:{I:X,c:"text-m-rose"},action_failed:{I:AlertCircle,c:"text-m-rose"},action_retried:{I:RotateCcw,c:"text-m-copper"},stepup_auth_triggered:{I:ShieldAlert,c:"text-m-copper"},risk_rule_changed:{I:Settings2,c:"text-m-ice"},consent_receipt_exported:{I:Download,c:"text-m-mint"}};
export function AuditPanel(){const log=useStore(s=>s.auditLog),svcs=useStore(s=>s.services),addA=useStore(s=>s.addAudit);const[exp,setExp]=useState(false);
  const xprt=async()=>{setExp(true);try{const{generateConsentReceipt}=await import("@/lib/consent-receipt");const b=await generateConsentReceipt(log,svcs);const u=URL.createObjectURL(b);const a=document.createElement("a");a.href=u;a.download=`mandate-receipt-${new Date().toISOString().slice(0,10)}.pdf`;a.click();URL.revokeObjectURL(u);addA("consent_receipt_exported","Exported receipt");}catch(e){console.error(e);}setExp(false);};
  if(!log.length)return<div className="flex flex-col items-center justify-center p-10 text-center"><div className="w-14 h-14 rounded-2xl bg-m-obsidian border border-m-edge flex items-center justify-center mb-4"><ScrollText className="h-6 w-6 text-m-ghost"/></div><p className="text-sm font-display font-semibold text-m-bone">No Activity</p><p className="text-[11px] text-m-ghost max-w-[220px] mt-1">Actions logged here.</p></div>;
  return(<div className="p-4 md:p-5"><div className="flex items-center justify-between mb-3"><span className="text-[8px] font-mono font-semibold uppercase tracking-[.12em] text-m-ghost">{log.length} events</span><button onClick={xprt} disabled={exp} className="flex items-center gap-1.5 rounded-lg bg-m-copper-dim border border-m-copper/10 px-2.5 py-1.5 text-[10px] font-medium text-m-copper disabled:opacity-50">{exp?<Loader2 className="h-3 w-3 animate-spin"/>:<Download className="h-3 w-3"/>}Export Receipt</button></div><div className="space-y-0.5">{log.map(e=>{const cfg=ec[e.type]??{I:Zap,c:"text-m-ghost"};const Icon=cfg.I;return(<div key={e.id} className="flex items-start gap-2.5 rounded-lg px-2.5 py-2 hover:bg-m-obsidian/50 animate-fade-up"><div className={`mt-0.5 ${cfg.c}`}><Icon className="h-3 w-3"/></div><div className="flex-1"><p className="text-[11px] text-m-bone">{e.message}</p><span className="text-[9px] font-mono text-m-ghost">{new Date(e.timestamp).toLocaleTimeString([],{hour:"2-digit",minute:"2-digit",second:"2-digit"})}</span>{e.service&&<span className="text-[9px] font-mono text-m-ghost bg-m-edge/50 rounded px-1.5 py-0.5 ml-2">{e.service}</span>}</div></div>);})}</div></div>);
}
