"use client";
import { Settings2,RotateCcw } from "lucide-react";
import { useStore } from "@/lib/store";
import type { RiskLevel } from "@/types";
import { RISK_META } from "@/types";
const RL:RiskLevel[]=["auto","confirm","approve","stepup"];
export function RiskRulesPanel(){const svcs=useStore(s=>s.services),ov=useStore(s=>s.riskOverrides),setOv=useStore(s=>s.setRiskOverride);const conn=svcs.filter(s=>s.connected);
  if(!conn.length)return<div className="flex flex-col items-center justify-center p-10 text-center"><div className="w-14 h-14 rounded-2xl bg-m-obsidian border border-m-edge flex items-center justify-center mb-4"><Settings2 className="h-6 w-6 text-m-ghost"/></div><p className="text-sm font-display font-semibold text-m-bone">No Services</p><p className="text-[11px] text-m-ghost max-w-[240px] mt-1">Connect services first.</p></div>;
  return(<div className="p-4 md:p-5 space-y-4"><div className="rounded-xl border border-m-edge bg-m-obsidian/50 px-3.5 py-3"><p className="text-xs font-display font-semibold text-m-white mb-1">Custom Risk Rules</p><p className="text-[10px] text-m-ghost">Override risk per scope. Your trust model, encoded.</p></div><div className="flex flex-wrap gap-2">{RL.map(r=>{const m=RISK_META[r];return<div key={r} className="flex items-center gap-1.5 rounded-full px-2.5 py-1 border" style={{background:m.bg,borderColor:m.border}}><div className="w-2 h-2 rounded-full" style={{background:m.color}}/><span className="text-[10px] font-medium" style={{color:m.color}}>{m.label}</span><span className="text-[8px] text-m-ghost">— {m.desc}</span></div>;})}</div>{conn.map(s=><div key={s.id} className="rounded-xl border border-m-edge bg-m-obsidian overflow-hidden"><div className="flex items-center gap-2.5 px-3.5 py-2.5 border-b border-m-edge/50"><div className="w-7 h-7 rounded-lg flex items-center justify-center text-[10px] font-bold font-mono" style={{background:s.gradient,color:s.iconColor}}>{s.icon}</div><span className="text-xs font-display font-semibold text-m-white">{s.name}</span></div>{s.scopes.map(sc=>{const cur=ov[`${s.id}.${sc.id}`]??sc.defaultRisk;const isO=ov[`${s.id}.${sc.id}`]&&ov[`${s.id}.${sc.id}`]!==sc.defaultRisk;return(<div key={sc.id} className="flex items-center gap-3 px-3.5 py-2.5 border-t border-m-edge/15"><div className="flex-1"><p className="text-[11px] text-m-bone">{sc.label}</p><p className="text-[9px] text-m-ghost">Default: <span style={{color:RISK_META[sc.defaultRisk].color}}>{RISK_META[sc.defaultRisk].label}</span>{isO&&<span className="text-m-ice"> → {RISK_META[cur].label}</span>}</p></div><div className="flex gap-0.5 bg-m-void rounded-lg p-0.5 border border-m-edge/50">{RL.map(r=>{const m=RISK_META[r];const on=cur===r;return<button key={r} onClick={()=>setOv(s.id,sc.id,r)} className="px-2 py-1 rounded-md text-[9px] font-medium" style={{background:on?m.bg:"transparent",color:on?m.color:"#4a4a6a",border:on?`1px solid ${m.border}`:"1px solid transparent"}}>{m.label}</button>;})}</div>{isO&&<button onClick={()=>setOv(s.id,sc.id,sc.defaultRisk)} className="w-6 h-6 rounded-md flex items-center justify-center text-m-ghost"><RotateCcw className="h-3 w-3"/></button>}</div>);})}</div>)}</div>);
}
