"use client";
import { useState } from "react";
import { Link2,Unlink,ChevronDown,ChevronUp,ToggleLeft,ToggleRight } from "lucide-react";
import { useStore } from "@/lib/store";
import type { ConnectedService,RiskLevel,TokenHealth } from "@/types";
import { RISK_META } from "@/types";
const hC:Record<TokenHealth,{l:string;c:string}>={active:{l:"Active",c:"text-m-mint"},expiring:{l:"Expiring",c:"text-m-copper"},expired:{l:"Expired",c:"text-m-rose"},revoked:{l:"Revoked",c:"text-m-rose"},missing:{l:"—",c:"text-m-ghost"}};

export function ServicesPanel(){const svcs=useStore(s=>s.services),cn=useStore(s=>s.connectService),dc=useStore(s=>s.disconnectService),tg=useStore(s=>s.toggleScope),ov=useStore(s=>s.riskOverrides);
  return(<div className="p-4 md:p-5 space-y-3"><div className="flex flex-wrap items-center gap-3 rounded-xl border border-m-edge bg-m-obsidian/50 px-3 py-2.5"><span className="text-[8px] font-mono font-semibold uppercase tracking-[.12em] text-m-ghost">Risk</span>{(Object.keys(RISK_META) as RiskLevel[]).map(l=><div key={l} className="flex items-center gap-1.5"><div className="w-2 h-2 rounded-full" style={{background:RISK_META[l].color}}/><span className="text-[10px] text-m-ghost">{RISK_META[l].label}</span></div>)}</div>{svcs.map(s=><SC key={s.id} s={s} onC={()=>cn(s.id)} onD={()=>dc(s.id)} onT={id=>tg(s.id,id)} ov={ov}/>)}</div>);}
function SC({s,onC,onD,onT,ov}:{s:ConnectedService;onC:()=>void;onD:()=>void;onT:(id:string)=>void;ov:Record<string,RiskLevel>}){const[op,setOp]=useState(false);const h=hC[s.tokenHealth];
  return(<div className={`rounded-xl border overflow-hidden ${s.connected?"border-m-copper/15 glow-copper":"border-m-edge"} bg-m-obsidian`}><div className="flex items-center gap-3 p-3 md:p-4"><div className="w-9 h-9 rounded-xl flex items-center justify-center text-xs font-bold font-mono flex-shrink-0" style={{background:s.gradient,color:s.iconColor}}>{s.icon}</div><div className="flex-1 min-w-0"><div className="flex items-center gap-2"><span className="text-[13px] font-display font-semibold text-m-white truncate">{s.name}</span>{s.connected&&<span className={`text-[10px] font-medium ${h.c}`}>{h.l}</span>}</div><p className="text-[10px] text-m-ghost truncate">{s.description}</p></div><div className="flex items-center gap-1.5 flex-shrink-0">{s.connected&&<button onClick={()=>setOp(!op)} className="w-7 h-7 rounded-lg flex items-center justify-center text-m-ghost hover:bg-m-void">{op?<ChevronUp className="h-4 w-4"/>:<ChevronDown className="h-4 w-4"/>}</button>}<button onClick={s.connected?onD:onC} className={`flex items-center gap-1 rounded-lg px-2.5 py-1.5 text-[11px] font-medium border ${s.connected?"bg-m-rose-dim border-m-rose/10 text-m-rose":"bg-m-copper-dim border-m-copper/10 text-m-copper"}`}>{s.connected?<><Unlink className="h-3 w-3"/>Revoke</>:<><Link2 className="h-3 w-3"/>Connect</>}</button></div></div>{s.connected&&op&&<div className="border-t border-m-edge/50 bg-m-void/30"><div className="px-3 py-2"><span className="text-[8px] font-mono font-semibold uppercase tracking-[.12em] text-m-ghost">Permissions</span></div>{s.scopes.map(sc=>{const er=ov[`${s.id}.${sc.id}`]||sc.defaultRisk;const rm=RISK_META[er];return(<div key={sc.id} className="flex items-center gap-3 px-3 py-2 border-t border-m-edge/20"><button onClick={()=>onT(sc.id)} className={`flex-shrink-0 ${sc.enabled?"text-m-mint":"text-m-ghost"}`}>{sc.enabled?<ToggleRight className="h-5 w-5"/>:<ToggleLeft className="h-5 w-5"/>}</button><div className="flex-1"><p className={`text-[11px] ${sc.enabled?"text-m-bone":"text-m-ghost line-through"}`}>{sc.label}</p></div><span className="text-[9px] font-medium rounded-full px-2 py-0.5" style={{color:rm.color,background:rm.bg}}>{rm.label}</span></div>);})}</div>}</div>);}